In [15]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics, svm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [16]:
from matplotlib import pyplot as plt

In [17]:
data = pd.read_csv('car.data')
print(data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [18]:
X = data[['buying', 'maint', 'safety']].values
y = data[['class']]
print(X,y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


In [19]:
#converting data_X
Le=LabelEncoder()
for i in range(len(X[0])):
  X[:,i]=Le.fit_transform(X[:,i])

print(X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [20]:
#converting data_y
label_maping={
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}
y['class']=y['class'].map(label_maping)
y=np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [22]:
#Creating model
knn=neighbors.KNeighborsClassifier(n_neighbors=25,weights='uniform')
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)
knn.fit(X_train,y_train)
prediction=knn.predict(X_test)
accuracy=metrics.accuracy_score(y_test,prediction)
print('Predictions: ',prediction)
print('Accuracy: ',accuracy)
print('Actual value: ',y[20])
print('Predicted value: ',knn.predict(X)[20])

Predictions:  [1 0 3 0 0 1 1 0 0 0 0 0 0 0 0 3 0 0 1 0 0 3 0 0 0 0 0 3 0 1 0 0 0 0 1 0 1
 0 0 0 0 0 0 3 0 1 0 0 1 0 1 0 1 0 1 1 1 0 0 0 0 3 0 3 1 0 0 0 1 0 0 0 0 1
 1 0 1 0 0 0 3 0 0 0 3 0 0 3 0 1 0 1 0 0 0 0 1 1 3 0 1 0 0 3 0 0 0 0 0 0 0
 0 1 0 0 0 1 0 0 0 3 3 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 3 1 1 1 3 0 0
 0 3 1 0 1 0 3 1 0 1 0 0 0 3 0 1 3 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 3 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1
 0 0 0 1 0 3 0 3 1 0 0 1 3 1 3 0 3 0 1 1 1 3 3 0 0 0 0 0 1 1 0 0 0 3 0 0 0
 0 3 0 0 0 0 0 0 0 0 0 3 3 1 0 0 1 0 0 0 1 3 1 1 3 0 0 1 1 0 0 0 0 0 1 0 0
 0 0 1 1 0 0 0 3 0 1 0 0 0 0 0 0 0 0 0 3 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 3
 0 0 0 0 0 0 0 0 0 0 0 3 0]
Accuracy:  0.7369942196531792
Actual value:  [0]
Predicted value:  0


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [23]:
#Creating Model
model=svm.SVC()
model.fit(X_train,y_train)
prediction=model.predict(X_test)
acc=metrics.accuracy_score(y_test,prediction)
print('Prediction: ',prediction)
print('Accuracy: ',acc)

Prediction:  [1 0 3 0 0 0 1 0 0 0 0 0 0 0 0 3 0 0 1 0 0 3 0 0 0 0 0 3 0 1 0 0 0 0 1 0 1
 0 0 0 0 0 0 3 0 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 3 0 3 1 0 0 0 1 0 0 0 0 1
 0 0 0 0 0 0 3 0 0 0 3 0 0 3 0 1 0 0 0 0 0 0 1 1 3 0 1 0 0 3 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 3 3 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 3 1 1 1 3 0 0
 0 3 1 0 1 0 3 1 0 0 0 0 0 3 0 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 3 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1
 0 0 0 1 0 3 0 3 0 0 0 1 3 1 3 0 3 0 0 0 1 3 3 0 0 0 0 0 1 1 0 0 0 3 0 0 0
 0 3 0 0 0 0 0 0 0 0 0 3 3 0 0 0 1 0 0 0 1 3 0 0 3 0 0 1 1 0 0 0 0 0 1 0 0
 0 0 1 0 0 0 0 3 0 1 0 0 0 0 0 0 0 0 0 3 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 3
 0 0 0 0 0 0 0 0 0 0 0 3 0]
Accuracy:  0.7109826589595376


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
